package com.plantcare.service;

import com.plantcare.dto.request.CareTaskRequest;
import com.plantcare.dto.response.CareTaskResponse;
import com.plantcare.entity.CareTask;
import com.plantcare.entity.Plant;
import com.plantcare.entity.User;
import com.plantcare.enums.TaskStatus;
import com.plantcare.enums.UserRole;
import com.plantcare.exception.CareScheduleException;
import com.plantcare.exception.PlantCareException;
import com.plantcare.exception.PlantNotFoundException;
import com.plantcare.repository.CareTaskRepository;
import com.plantcare.repository.PlantRepository;
import com.plantcare.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class CareTaskService {

    @Autowired
    private CareTaskRepository careTaskRepository;

    @Autowired
    private PlantRepository plantRepository;

    @Autowired
    private UserRepository userRepository;

    @Transactional
    public CareTaskResponse createTask(CareTaskRequest request, Long userId) {
        Plant plant = plantRepository.findById(request.getPlantId())
                .orElseThrow(() -> new PlantNotFoundException(request.getPlantId()));
        checkPlantAccess(plant, userId);

        if (request.getScheduledDate().isAfter(LocalDateTime.now().plusDays(30))) {
            throw new CareScheduleException("Care tasks cannot be scheduled more than 30 days in advance");
        }

        CareTask task = new CareTask();
        task.setPlant(plant);
        task.setTaskType(request.getTaskType());
        task.setScheduledDate(request.getScheduledDate());
        task.setStatus(TaskStatus.PENDING);
        task.setPriority(request.getPriority());
        task.setNotes(request.getNotes());
        task.setAutoGenerated(false);
        task.setReminderSent(false);

        return mapToResponse(careTaskRepository.save(task));
    }

    public CareTaskResponse getTaskById(Long taskId, Long userId) {
        CareTask task = careTaskRepository.findById(taskId)
                .orElseThrow(() -> new PlantCareException("Task not found"));
        checkPlantAccess(task.getPlant(), userId);
        return mapToResponse(task);
    }

    @Transactional
    public CareTaskResponse updateTask(Long taskId, CareTaskRequest request, Long userId) {
        CareTask task = careTaskRepository.findById(taskId)
                .orElseThrow(() -> new PlantCareException("Task not found"));
        checkPlantAccess(task.getPlant(), userId);

        if (request.getTaskType() != null) task.setTaskType(request.getTaskType());
        if (request.getScheduledDate() != null) task.setScheduledDate(request.getScheduledDate());
        if (request.getPriority() != null) task.setPriority(request.getPriority());
        if (request.getNotes() != null) task.setNotes(request.getNotes());

        return mapToResponse(careTaskRepository.save(task));
    }

    @Transactional
    public void deleteTask(Long taskId, Long userId) {
        CareTask task = careTaskRepository.findById(taskId)
                .orElseThrow(() -> new PlantCareException("Task not found"));
        checkPlantAccess(task.getPlant(), userId);
        careTaskRepository.delete(task);
    }

    @Transactional
    public CareTaskResponse completeTask(Long taskId, Long userId) {
        CareTask task = careTaskRepository.findById(taskId)
                .orElseThrow(() -> new PlantCareException("Task not found"));
        checkPlantAccess(task.getPlant(), userId);

        task.setStatus(TaskStatus.COMPLETED);
        task.setCompletedDate(LocalDateTime.now());

        User user = userRepository.findById(userId).orElseThrow();
        task.setCompletedBy(user);

        Plant plant = task.getPlant();
        switch (task.getTaskType()) {
            case WATERING: plant.setLastWateredDate(LocalDateTime.now()); break;
            case FERTILIZING: plant.setLastFertilizedDate(LocalDateTime.now()); break;
            case PRUNING: plant.setLastPrunedDate(LocalDateTime.now()); break;
            case REPOTTING: plant.setLastRepottedDate(LocalDateTime.now()); break;
            default: break;
        }
        plantRepository.save(plant);

        return mapToResponse(careTaskRepository.save(task));
    }

    public List<CareTaskResponse> getUpcomingTasks(Long userId) {
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime weekAhead = now.plusDays(7);
        return careTaskRepository.findUpcomingTasksByOwner(userId, now, weekAhead, List.of(TaskStatus.PENDING))
                .stream().map(this::mapToResponse).collect(Collectors.toList());
    }

    public List<CareTaskResponse> getOverdueTasks(Long userId) {
        return careTaskRepository.findOverdueTasksByOwner(userId, LocalDateTime.now())
                .stream().map(this::mapToResponse).collect(Collectors.toList());
    }

    private void checkPlantAccess(Plant plant, Long userId) {
        User user = userRepository.findById(userId).orElseThrow(() -> new PlantCareException("User not found"));
        if (user.getRole() == UserRole.ADMIN || user.getRole() == UserRole.PLANT_CARE_SPECIALIST) {
            return;
        }
        if (!plant.getOwner().getId().equals(userId)) {
            throw new PlantCareException("Access denied to this plant");
        }
    }

    private CareTaskResponse mapToResponse(CareTask task) {
        return CareTaskResponse.builder()
                .id(task.getId())
                .plantId(task.getPlant().getId())
                .plantNickname(task.getPlant().getNickname())
                .taskType(task.getTaskType())
                .scheduledDate(task.getScheduledDate())
                .completedDate(task.getCompletedDate())
                .status(task.getStatus())
                .priority(task.getPriority())
                .notes(task.getNotes())
                .reminderSent(task.getReminderSent())
                .autoGenerated(task.getAutoGenerated())
                .createdDate(task.getCreatedDate())
                .build();
    }
}
