package com.plantcare.service;

import com.plantcare.dto.request.PlantCreateRequest;
import com.plantcare.dto.request.PlantSearchRequest;
import com.plantcare.dto.response.CareTaskResponse;
import com.plantcare.dto.response.DashboardSummary;
import com.plantcare.dto.response.PlantResponse;
import com.plantcare.entity.CareTask;
import com.plantcare.entity.Plant;
import com.plantcare.entity.Species;
import com.plantcare.entity.User;
import com.plantcare.enums.HealthStatus;
import com.plantcare.enums.TaskPriority;
import com.plantcare.enums.TaskStatus;
import com.plantcare.enums.TaskType;
import com.plantcare.enums.UserRole;
import com.plantcare.exception.PlantCareException;
import com.plantcare.exception.PlantNotFoundException;
import com.plantcare.repository.CareTaskRepository;
import com.plantcare.repository.PlantRepository;
import com.plantcare.repository.SpeciesRepository;
import com.plantcare.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class PlantService {

    @Autowired
    private PlantRepository plantRepository;

    @Autowired
    private SpeciesRepository speciesRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CareTaskRepository careTaskRepository;

    @Transactional
    public PlantResponse createPlant(Long ownerId, PlantCreateRequest request) {
        User owner = userRepository.findById(ownerId)
                .orElseThrow(() -> new PlantCareException("User not found"));

        Species species = speciesRepository.findById(request.getSpeciesId())
                .orElseThrow(() -> new PlantCareException("Species not found"));

        Plant plant = new Plant();
        plant.setOwner(owner);
        plant.setSpecies(species);
        plant.setNickname(request.getNickname());
        plant.setLocation(request.getLocation());
        plant.setAcquisitionDate(request.getAcquisitionDate());
        plant.setCurrentHeightCm(request.getCurrentHeightCm());
        plant.setCurrentWidthCm(request.getCurrentWidthCm());
        plant.setPotSize(request.getPotSize());
        plant.setSoilType(request.getSoilType());
        plant.setNotes(request.getNotes());
        plant.setHealthStatus(HealthStatus.GOOD);
        plant.setIsActive(true);

        Plant savedPlant = plantRepository.save(plant);
        generateInitialCareSchedule(savedPlant);

        return mapToResponse(savedPlant);
    }

    private void generateInitialCareSchedule(Plant plant) {
        Species species = plant.getSpecies();
        LocalDateTime now = LocalDateTime.now();

        if (species.getWaterFrequencyDays() != null && species.getWaterFrequencyDays() > 0) {
            CareTask task = new CareTask();
            task.setPlant(plant);
            task.setTaskType(TaskType.WATERING);
            task.setScheduledDate(now.plusDays(species.getWaterFrequencyDays()));
            task.setStatus(TaskStatus.PENDING);
            task.setPriority(TaskPriority.MEDIUM);
            task.setAutoGenerated(true);
            careTaskRepository.save(task);
        }

        if (species.getFertilizerFrequencyDays() != null && species.getFertilizerFrequencyDays() > 0) {
            CareTask task = new CareTask();
            task.setPlant(plant);
            task.setTaskType(TaskType.FERTILIZING);
            task.setScheduledDate(now.plusDays(species.getFertilizerFrequencyDays()));
            task.setStatus(TaskStatus.PENDING);
            task.setPriority(TaskPriority.LOW);
            task.setAutoGenerated(true);
            careTaskRepository.save(task);
        }
    }

    public PlantResponse getPlantById(Long plantId, Long userId) {
        Plant plant = plantRepository.findById(plantId)
                .orElseThrow(() -> new PlantNotFoundException(plantId));
        checkPlantAccess(plant, userId);
        return mapToResponse(plant);
    }

    @Transactional
    public PlantResponse updatePlant(Long plantId, Long userId, PlantCreateRequest request) {
        Plant plant = plantRepository.findById(plantId)
                .orElseThrow(() -> new PlantNotFoundException(plantId));
        checkPlantAccess(plant, userId);

        if (request.getNickname() != null) plant.setNickname(request.getNickname());
        if (request.getLocation() != null) plant.setLocation(request.getLocation());
        if (request.getCurrentHeightCm() != null) plant.setCurrentHeightCm(request.getCurrentHeightCm());
        if (request.getCurrentWidthCm() != null) plant.setCurrentWidthCm(request.getCurrentWidthCm());
        if (request.getPotSize() != null) plant.setPotSize(request.getPotSize());
        if (request.getSoilType() != null) plant.setSoilType(request.getSoilType());
        if (request.getNotes() != null) plant.setNotes(request.getNotes());

        return mapToResponse(plantRepository.save(plant));
    }

    @Transactional
    public void deletePlant(Long plantId, Long userId) {
        Plant plant = plantRepository.findById(plantId)
                .orElseThrow(() -> new PlantNotFoundException(plantId));
        checkPlantAccess(plant, userId);
        plant.setIsActive(false);
        plantRepository.save(plant);
    }

    public Page<PlantResponse> getPlantsByOwner(Long ownerId, int page, int size, String sort) {
        Pageable pageable = PageRequest.of(page, size, Sort.by(sort != null ? sort : "nickname").ascending());
        Page<Plant> plants = plantRepository.findActiveByOwnerId(ownerId, pageable);
        return plants.map(this::mapToResponse);
    }

    public Page<PlantResponse> searchPlants(Long ownerId, PlantSearchRequest request, int page, int size) {
        Pageable pageable = PageRequest.of(page, size);
        Page<Plant> plants = plantRepository.findPlantsWithFilters(
                ownerId, request.getNickname(), request.getSpeciesName(),
                request.getHealthStatus(), request.getLocation(), pageable);
        return plants.map(this::mapToResponse);
    }

    public List<PlantResponse> getPlantsNeedingAttention(Long ownerId) {
        return plantRepository.findPlantsNeedingAttention(ownerId)
                .stream().map(this::mapToResponse).collect(Collectors.toList());
    }

    public DashboardSummary getDashboardSummary(Long ownerId) {
        List<Plant> allPlants = plantRepository.findByOwnerIdAndIsActiveTrue(ownerId);
        List<Plant> needingAttention = plantRepository.findPlantsNeedingAttention(ownerId);

        LocalDateTime now = LocalDateTime.now();
        LocalDateTime weekAhead = now.plusDays(7);
        List<CareTask> upcomingTasks = careTaskRepository.findUpcomingTasksByOwner(
                ownerId, now, weekAhead, List.of(TaskStatus.PENDING));
        List<CareTask> overdueTasks = careTaskRepository.findOverdueTasksByOwner(ownerId, now);
        Long completedThisWeek = careTaskRepository.countByPlantOwnerIdAndStatus(ownerId, TaskStatus.COMPLETED);

        Map<String, Long> healthMap = new HashMap<>();
        for (HealthStatus status : HealthStatus.values()) {
            healthMap.put(status.name(), allPlants.stream()
                    .filter(p -> p.getHealthStatus() == status).count());
        }

        return DashboardSummary.builder()
                .totalPlants((long) allPlants.size())
                .plantsNeedingAttention((long) needingAttention.size())
                .upcomingTasks((long) upcomingTasks.size())
                .overdueTasks((long) overdueTasks.size())
                .completedTasksThisWeek(completedThisWeek != null ? completedThisWeek : 0L)
                .plantsByHealthStatus(healthMap)
                .upcomingTasksList(upcomingTasks.stream().map(this::mapTaskToResponse).collect(Collectors.toList()))
                .plantsNeedingAttentionList(needingAttention.stream().map(this::mapToResponse).collect(Collectors.toList()))
                .build();
    }

    @Transactional
    public PlantResponse updateHealthStatus(Long plantId, Long userId, HealthStatus status) {
        Plant plant = plantRepository.findById(plantId)
                .orElseThrow(() -> new PlantNotFoundException(plantId));
        checkPlantAccess(plant, userId);
        plant.setHealthStatus(status);
        return mapToResponse(plantRepository.save(plant));
    }

    private void checkPlantAccess(Plant plant, Long userId) {
        User user = userRepository.findById(userId).orElseThrow(() -> new PlantCareException("User not found"));
        if (user.getRole() == UserRole.ADMIN || user.getRole() == UserRole.PLANT_CARE_SPECIALIST) {
            return;
        }
        if (!plant.getOwner().getId().equals(userId)) {
            throw new PlantCareException("Access denied to this plant");
        }
    }

    private PlantResponse mapToResponse(Plant plant) {
        return PlantResponse.builder()
                .id(plant.getId())
                .ownerId(plant.getOwner().getId())
                .ownerUsername(plant.getOwner().getUsername())
                .speciesId(plant.getSpecies().getId())
                .speciesCommonName(plant.getSpecies().getCommonName())
                .speciesScientificName(plant.getSpecies().getScientificName())
                .nickname(plant.getNickname())
                .location(plant.getLocation())
                .acquisitionDate(plant.getAcquisitionDate())
                .currentHeightCm(plant.getCurrentHeightCm())
                .currentWidthCm(plant.getCurrentWidthCm())
                .potSize(plant.getPotSize())
                .soilType(plant.getSoilType())
                .lastWateredDate(plant.getLastWateredDate())
                .lastFertilizedDate(plant.getLastFertilizedDate())
                .lastPrunedDate(plant.getLastPrunedDate())
                .lastRepottedDate(plant.getLastRepottedDate())
                .healthStatus(plant.getHealthStatus())
                .notes(plant.getNotes())
                .isActive(plant.getIsActive())
                .createdDate(plant.getCreatedDate())
                .updatedDate(plant.getUpdatedDate())
                .build();
    }

    private CareTaskResponse mapTaskToResponse(CareTask task) {
        return CareTaskResponse.builder()
                .id(task.getId())
                .plantId(task.getPlant().getId())
                .plantNickname(task.getPlant().getNickname())
                .taskType(task.getTaskType())
                .scheduledDate(task.getScheduledDate())
                .completedDate(task.getCompletedDate())
                .status(task.getStatus())
                .priority(task.getPriority())
                .notes(task.getNotes())
                .reminderSent(task.getReminderSent())
                .autoGenerated(task.getAutoGenerated())
                .build();
    }
}
