export enum TaskType {
  WATERING = 'WATERING',
  FERTILIZING = 'FERTILIZING',
  PRUNING = 'PRUNING',
  REPOTTING = 'REPOTTING',
  MISTING = 'MISTING',
  OTHER = 'OTHER'
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export interface CareTaskResponse {
  id: number;
  plantId: number;
  plantNickname?: string;
  taskType: TaskType;
  title?: string;
  description?: string;
  scheduledDate: string;
  completedDate?: string;
  status: TaskStatus;
  priority: TaskPriority;
  notes?: string;
  reminderSent?: boolean;
  autoGenerated?: boolean;
  createdDate?: string;
  updatedDate?: string;
}

export interface CareTaskRequest {
  plantId: number;
  taskType: TaskType;
  title?: string;
  description?: string;
  scheduledDate: string;
  scheduledTime?: string;
  priority?: TaskPriority;
  notes?: string;
}
