package com.plantcare.dto.response;

import com.plantcare.enums.TaskPriority;
import com.plantcare.enums.TaskStatus;
import com.plantcare.enums.TaskType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CareTaskResponse {
    private Long id;
    private Long plantId;
    private String plantNickname;
    private TaskType taskType;
    private LocalDateTime scheduledDate;
    private LocalDateTime completedDate;
    private TaskStatus status;
    private TaskPriority priority;
    private String notes;
    private Boolean reminderSent;
    private Boolean autoGenerated;
    private LocalDateTime createdDate;
}
